# Generated by Django 2.2.13 on 2022-01-22 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('filename', models.CharField(max_length=128, verbose_name='文件名')),
                ('md5_name', models.CharField(max_length=64, verbose_name='加密名称')),
                ('tags', models.CharField(blank=True, max_length=255, null=True, verbose_name='标识')),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='上传时间')),
                ('removed', models.IntegerField(default=0, verbose_name='已删除')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
